Update patch set 5
Patch Set 5:

Last failure due to infra issues

WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPConnection object at 0x7f8748e00748>, 'Connection to mirror.gra1.ovh.openstack.org timed out. (connect timeout=60.0)')': /wheel/ubuntu-18.04-x86_64/coverage/
ERROR: Could not find a version that satisfies the requirement coverage>=3.6 (from -r /home/zuul/src/opendev.org/x/charm-ovn-central/test-requirements.txt (line 6)) (from versions: none)

Patch-set: 5