Update patch set 3
Patch Set 3:

Focal test fails due to bug in ``layer-basic``: https://github.com/juju-solutions/layer-basic/pull/156

    distutils.errors.DistutilsError: the `allow-hosts` option is not supported when using pip to install requirements.

Patch-set: 3