Update patch set 5
Patch Set 5:

Another failure due to infra issues

WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPConnection object at 0x7f3da410aba8>, 'Connection to mirror.gra1.ovh.openstack.org timed out. (connect timeout=60.0)')': /wheel/ubuntu-18.04-x86_64/charm-tools/
ERROR: Could not find a version that satisfies the requirement charm-tools>=2.4.4 (from -r /home/zuul/src/opendev.org/x/charm-ovn-central/requirements.txt (line 6)) (from versions: none)

Patch-set: 5